# Generated by Django 3.2.18 on 2024-04-26 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.group'),
            preserve_default=False,
        ),
    ]
