# Generated by Django 3.2.18 on 2024-04-27 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20240426_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auther',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
    ]
