# Generated by Django 3.2.18 on 2024-04-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_group_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='auther',
            new_name='author',
        ),
    ]
