# Generated by Django 3.2.18 on 2024-04-27 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_auther_group_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharing',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
